### ISSUE TITLE
The application crashes in the docker container

### ISSUE THREAD

**Issue by michaa76** [loopingz/aws-smtp-relay#28]
## Steps to reproduce the behavior
starting the docker container and sending email requests leads to application crash with the following log:

	at com.amazonaws.regions.AwsRegionProviderChain.<clinit>(AwsRegionProviderChain.java:33)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:232)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.amazonaws.client.builder.AwsClientBuilder.<clinit>(AwsClientBuilder.java:60)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:232)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:232)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.loopingz.AwsSmtpRelay.deliver(AwsSmtpRelay.java:38)
	at org.subethamail.smtp.helper.SimpleMessageListenerAdapter$Handler.data(SimpleMessageListenerAdapter.java:142)
	at org.subethamail.smtp.command.DataCommand.execute(DataCommand.java:64)
	at org.subethamail.smtp.server.RequireTLSCommandWrapper.execute(RequireTLSCommandWrapper.java:30)
	at org.subethamail.smtp.server.CommandHandler.handleCommand(CommandHandler.java:99)
	at org.subethamail.smtp.server.Session.runCommandLoop(Session.java:244)
	at org.subethamail.smtp.server.Session.run(Session.java:145)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Exception in thread "pool-2-thread-1" java.lang.NoClassDefFoundError: org.apache.commons.logging.LogFactory
	at org.apache.commons.logging.LogFactory.class$(LogFactory.java:847)
	at org.apache.commons.logging.LogFactory.<clinit>(LogFactory.java:1717)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.amazonaws.regions.AwsRegionProviderChain.<clinit>(AwsRegionProviderChain.java:33)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:232)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.amazonaws.client.builder.AwsClientBuilder.<clinit>(AwsClientBuilder.java:60)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:232)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:232)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at com.loopingz.AwsSmtpRelay.deliver(AwsSmtpRelay.java:38)
	at org.subethamail.smtp.helper.SimpleMessageListenerAdapter$Handler.data(SimpleMessageListenerAdapter.java:142)
	at org.subethamail.smtp.command.DataCommand.execute(DataCommand.java:64)
	at org.subethamail.smtp.server.RequireTLSCommandWrapper.execute(RequireTLSCommandWrapper.java:30)
	at org.subethamail.smtp.server.CommandHandler.handleCommand(CommandHandler.java:99)
	at org.subethamail.smtp.server.Session.runCommandLoop(Session.java:244)
	at org.subethamail.smtp.server.Session.run(Session.java:145)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

**Comment by loopingz** [comment]
Which version do you use? The 1.2 has been compiled with GraalVM, you might want to try the 1.1 to confirm the behavior

**Comment by loopingz** [comment]
It means we need to add some unit/integration testing as well

**Comment by loopingz** [comment]
Closing this issue as no feedback was provided, probably related to the GraalVM issue
